version: "3.7"
services:
  cumulus_granules_catalog:
    image: ghcr.io/unity-sds/unity-data-services:1.7.0
    command: ["CATALOG"]
    environment:
      AWS_ACCESS_KEY_ID: 'dd'
      AWS_SECRET_ACCESS_KEY: 'dddd'
      AWS_SESSION_TOKEN: 'dddd'
      AWS_REGION: 'us-west-2'

      PYTHONUNBUFFERED: 1

      UNITY_BEARER_TOKEN: 'token without the header "Bearer". The alternative is the following group'

      USERNAME: 'plain text | AWS parameter store key | base64 encoded str'
      PASSWORD: 'plain text | AWS parameter store key | base64 encoded str'
      PASSWORD_TYPE: 'PLAIN | PARAM_STORE | BASE64'
      CLIENT_ID: 'ask U-CS. ex: 7a1fglm2d54eoggj13lccivp25'
      COGNITO_URL: 'ask U-CS. ex: https://cognito-idp.us-west-2.amazonaws.com'

      VERIFY_SSL: 'FALSE'
      DAPA_API: 'https://k3a3qmarxh.execute-api.us-west-2.amazonaws.com/dev'

      LOG_LEVEL: '20'

      PROVIDER_ID: 'SNPP'
      GRANULES_CATALOG_TYPE: 'UNITY'
      UPLOADED_FILES_JSON: '[{"id": "NEW_COLLECTION_EXAMPLE_L1B___9:test_file01", "collection": "NEW_COLLECTION_EXAMPLE_L1B___9", "assets": {"metadata": {"href": "s3://uds-test-cumulus-staging/NEW_COLLECTION_EXAMPLE_L1B___9:test_file01/test_file01.nc.cas"}, "data": {"href": "s3://uds-test-cumulus-staging/NEW_COLLECTION_EXAMPLE_L1B___9:test_file01/test_file01.nc"}}}]'

      DELAY_SECOND: '45'
      REPEAT_TIMES: '5'

    networks:
      - internal
networks:
  internal: