version: "3.7"
services:
  cumulus_granules_upload:
    image: ghcr.io/unity-sds/unity-data-services:1.7.0
    volumes:
      - /tmp/cumulus_granules:/etc/granules
    command: ["UPLOAD"]
    environment:
      AWS_ACCESS_KEY_ID: 'dd'
      AWS_SECRET_ACCESS_KEY: 'dddd'
      AWS_SESSION_TOKEN: 'dddd'
      AWS_REGION: 'us-west-2'

      PYTHONUNBUFFERED: 1

      UNITY_BEARER_TOKEN: 'token without the header "Bearer". The alternative is the following group'

      USERNAME: 'plain text | AWS parameter store key | base64 encoded str'
      PASSWORD: 'plain text | AWS parameter store key | base64 encoded str'
      PASSWORD_TYPE: 'PLAIN | PARAM_STORE | BASE64'
      CLIENT_ID: 'ask U-CS. ex: 7a1fglm2d54eoggj13lccivp25'
      COGNITO_URL: 'ask U-CS. ex: https://cognito-idp.us-west-2.amazonaws.com'

      VERIFY_SSL: 'FALSE'
      DRY_RUN: 'TRUE | FALSE . set to TRUE to confirm if all settings are correct bar aws credentials'
      DAPA_API: 'https://k3a3qmarxh.execute-api.us-west-2.amazonaws.com/dev'

      PROJECT: 'NAME of the project if collection name in Granule STAC purely includes the name. It will be part of URN:NASA:UNITY:<PROJECT>:<VENUE>:<NAME>'
      VENUE: 'VENUE of the project if collection name in Granule STAC purely includes the name. It will be part of URN:NASA:UNITY:<PROJECT>:<VENUE>:<NAME>'
      STAGING_BUCKET: 'uds-test-cumulus-staging'

      DELETE_FILES: 'FALSE'
      RESULT_PATH_PREFIX: 'stage_out/sample_dir  (Optional:defaulted to stage_out if missing. NOTE: No need to begin or end with "/". It also accepts empty string now as default value)'

      GRANULES_SEARCH_DOMAIN: 'UNITY'
      GRANULES_UPLOAD_TYPE: 'UPLOAD_S3_BY_STAC_CATALOG'
      UPLOAD_DIR: '/etc/snpp_upload_test_1. or empty string'
      OUTPUT_DIRECTORY: '/some/directory'
      CATALOG_FILE: 'empty string or /path/to/stac/catalog file'
      LOG_LEVEL: '20  NOTE: 10=DEBUG 20=info. 30=error'
    networks:
      - internal
networks:
  internal: