version: "3.7"
services:
  cumulus_granules_upload:
    image: stac-web-swervice-1.0:latest
    entrypoint: 'uvicorn web_service:app --host 0.0.0.0 --port 8005 --log-level info --reload'
    tty: true
    working_dir: '/usr/src/app/unity/cumulus_lambda_functions/uds_api'
    ports:
      - 8005:8005
    environment:
      AWS_ACCESS_KEY_ID: 'dd'
      AWS_SECRET_ACCESS_KEY: 'dddd'
      AWS_SESSION_TOKEN: 'dddd'
      AWS_REGION: 'us-west-2'

      PYTHONPATH: '${PYTHONPATH}:/usr/src/app/unity'

      COLLECTION_CREATION_LAMBDA_NAME: 'arn:aws:lambda:us-west-2:xxx:function:uds-sbx-cumulus-uds_api_1'
      CUMULUS_LAMBDA_PREFIX: 'uds-sbx-cumulus'
      CUMULUS_WORKFLOW_NAME: 'CatalogGranule'
      CUMULUS_WORKFLOW_SQS_URL: 'https://sqs.us-west-2.amazonaws.com/237868187491/uds-sbx-cumulus-cnm-submission-queue'
      LOG_LEVEL: '10'
      UNITY_DEFAULT_PROVIDER: 'unity'
      SNS_TOPIC_ARN: 'arn:aws:sns:us-west-2:xxx:uds-sbx-cumulus-cnm-submission-sns'
      ES_URL: 'vpc-uds-sbx-cumulus-es-xxx.us-west-2.es.amazonaws.com'
      ADMIN_COMMA_SEP_GROUPS: 'Unity_Admin'
      DAPA_API_PREIFX_KEY: 'data'
      STATIC_PARENT_DIR: '/usr/src/app/unity/cumulus_lambda_functions/uds_api/'
      CUMULUS_BASE: 'https://na/dev'
      ES_PORT: '443'
      REPORT_TO_EMS: 'FALSE'
    networks:
      - internal
networks:
  internal: