name: Build Docker file CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

env:
  REGISTRY: ghcr.io
  software_version: 0.0.1
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to ghcr
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: wphyojpl
          password: ${{ secrets.ghcr_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./docker/Dockerfile_download_granules.public
          push: true
          tags: "${{ env.REGISTRY }}/unity/uds_download_granules:v${{ env.software_version }}"
