name: Makefile CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

env:
  ARTIFACT_BASE_NAME: cumulus_lambda_functions
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.7'
    - run: |
        python3 "${GITHUB_WORKSPACE}/setup.py" install
    - run: |
        python3 "${GITHUB_WORKSPACE}/setup.py" install_lib
    - run: |
        # make file runnable, might not be necessary
        chmod +x "${GITHUB_WORKSPACE}/ci.cd/create_aws_lambda_zip.sh"

        # run script
        "${GITHUB_WORKSPACE}/ci.cd/create_aws_lambda_zip.sh"

    - name: Create Release
      id: create_release
      if: ${{ contains(github.ref, 'master') }}
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: "v${{ env.software_version }}"
        release_name: "Release v${{ env.software_version }} - ${{ github.ref }}"
        body: |
          Changes in this release:
          ${{ github.event.head_commit.message }}
        body_path: release.md
        draft: false
        prerelease: false
    - name: Create PreRelease
      id: create_prerelease
      if: ${{ contains(github.ref, 'develop') }}
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: "v${{ env.software_version }}"
        release_name: "Release v${{ env.software_version }} - ${{ github.ref }}"
        body: |
          Changes in this release:
          ${{ github.event.head_commit.message }}
        draft: false
        prerelease: true
    - name: Upload PreRelease Asset
      id: upload-prerelease-asset
      if: ${{ contains(github.ref, 'develop') }}
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_prerelease.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
        asset_path: "${{ env.ARTIFACT_FILE }}"
        asset_name: "${{ env.ARTIFACT_FILE }}"
        asset_content_type: application/zip
    - name: Upload Release Asset
      id: upload-release-asset
      if: ${{ contains(github.ref, 'master') }}
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
        asset_path: "${{ env.ARTIFACT_FILE }}"
        asset_name: "${{ env.ARTIFACT_FILE }}"
        asset_content_type: application/zip