name: Build PR Merge
on:
  pull_request:
    types: [ closed ]

env:
  ARTIFACT_BASE_NAME: cumulus_lambda_functions
  PR_NUMBER: ${{ github.event.number }}
  PR_TITLE: ${{ github.event.pull_request.title }}
  PAT_TOKEN: ${{ secrets.PAT_SECRET }}
  GH_TOKEN: ${{ github.token }}
jobs:
  if_merged:
    if: github.event.pull_request.merged == true && !(contains(github.event.pull_request.title, 'update version + change log'))
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - run: |
          # make file runnable, might not be necessary
          chmod +x "${GITHUB_WORKSPACE}/ci.cd/store_version.sh"
          echo "what the ..."
          "${GITHUB_WORKSPACE}/ci.cd/store_version.sh"
      - run: |
          artifact_file_name="${{ env.ARTIFACT_BASE_NAME }}-${{ env.software_version }}.zip"
          echo "${PR_TITLE} -- ${PR_NUMBER}"
      - run: |
          python3 "${GITHUB_WORKSPACE}/ci.cd/update_setup_version.py" install
      - run: |
          chmod +x "${GITHUB_WORKSPACE}/ci.cd/update_version_commit.sh"
          "${GITHUB_WORKSPACE}/ci.cd/update_version_commit.sh"
