name: Build PR Merge
on:
  pull_request:
    types: [closed]

env:
  ARTIFACT_BASE_NAME: cumulus_lambda_functions
jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - run: |
        artifact_file_name="${{ env.ARTIFACT_BASE_NAME }}-${{ env.software_version }}.zip"
        PR_NUMBER="${{ github.event.number }}"
        PR_TITLE="${{ github.event.pull_request.title }}"
        echo "${PR_TITLE} -- ${PR_NUMBER}"
